Repository buildwithgrove/path, pull requests merged in 2024-12, with the labels that each got.

#58 Localnet tilt v0
  Makefile
  Tiltfile
  cmd/main.go
  docker-compose.yml
  e2e/docker_test.go
  local/kubernetes/observability-loki-stack.yaml
  local/kubernetes/observability-prometheus-stack.yaml
  local/path/config/morse.example.yaml
  local/path/config/shannon.example.yaml
  local_config.yaml
Labels: localnet

#52 [ENVOY][AUTH] feat: remove DB dep and use gRPC for `GatewayEndpoint` data
  Makefile
  README.md
  config/config.schema.yaml
  config/testdata/morse.example.yaml
  config/testdata/shannon.example.yaml
  e2e/morse.example.yaml
  envoy/README.md
  envoy/auth_plugin/db/cache.go
  envoy/auth_plugin/db/cache_test.go
  envoy/auth_plugin/db/driver.go
  envoy/auth_plugin/db/driver_mock_test.go
  envoy/auth_plugin/db/postgres/db.generated.go
  envoy/auth_plugin/db/postgres/docker_test.go
  envoy/auth_plugin/db/postgres/driver.go
  envoy/auth_plugin/db/postgres/driver_test.go
  envoy/auth_plugin/db/postgres/models.generated.go
  envoy/auth_plugin/db/postgres/query.sql.generated.go
  envoy/auth_plugin/db/postgres/sqlc/query.sql
  envoy/auth_plugin/db/postgres/sqlc/schema.sql
  envoy/auth_plugin/db/postgres/sqlc/sqlc.yaml
  envoy/auth_plugin/db/postgres/testdata/seed-test-db.sql
  envoy/auth_plugin/go.mod
  envoy/auth_plugin/go.sum
  envoy/auth_plugin/user/gateway_endpoint.go
  envoy/auth_server/.env.example
  envoy/auth_server/Dockerfile
  envoy/auth_server/auth/auth_handler.go
  envoy/auth_server/auth/auth_handler_test.go
  envoy/auth_server/auth/authorizer.go
  envoy/auth_server/auth/authorizer_api_key.go
  envoy/auth_server/auth/authorizer_jwt.go
  envoy/auth_server/auth/endpoint_store_mock_test.go
  envoy/auth_server/endpoint_store/client_mock_test.go
  envoy/auth_server/endpoint_store/endpoint_store.go
  envoy/auth_server/endpoint_store/endpoint_store_test.go
  envoy/auth_server/go.mod
  envoy/auth_server/go.sum
  envoy/auth_server/main.go
  envoy/auth_server/proto/gateway_endpoint.pb.go
  envoy/auth_server/proto/gateway_endpoint.proto
  envoy/auth_server/proto/gateway_endpoint_grpc.pb.go
  envoy/envoy.template.yaml
  envoy/ratelimit.yaml
  envoy/scripts/copy_envoy_config.sh
  envoy/scripts/copy_gateway_endpoints_yaml.sh
  go.mod
  go.sum
Labels: enhancement, rate limiter, envoy

#75 fix: update to run E2E tests for morse/shannon in parallel
  .github/workflows/run-tests.yml
  Makefile
  config/config.schema.yaml
  e2e/morse.example.yaml
  protocol/morse/protocol.go
  test_.sh
Labels: enhancement, infra

#80 [Docs] Add MIT license
  LICENSE
  README.md
Labels: documentation

#85 Update Shannon E2E config with Shannon Beta Testnet URLs
  e2e/shannon.example.yaml
Labels: E2E

#79 [Logging] Add logging in the HTTP request processing path
  gateway/gateway.go
Labels: enhancement

#83 [READY] Change trigger workflow from workflow_run to push
  .github/workflows/release-artifacts.yml
Labels: bug

#84 Update Makefile config copy location
  Makefile
Labels: bug

#74 [READY] Localnet configuration parity with staging
  Makefile
  README.md
  Tiltfile
  docusaurus/docs/README.md
  local/path/config/path-values.yaml
  makefiles/localnet.mk
Labels: documentation, enhancement

#91 Update README.md with new make targets
  Makefile
  README.md
  docusaurus/docs/README.md
  envoy/README.md
Labels: tooling

#86 Update EVM service timeout to 10s
  qos/evm/context.go
  qos/evm/endpoint.go
Labels: qos

#92 fix: consolidate config files under ./config/examples
  Makefile
  README.md
  cmd/.config.morse_example.yaml
  cmd/.config.morse_example_testnet.yaml
  cmd/.config.shannon_example.yaml
  config/config_test.go
  config/examples/config.morse_example.yaml
  config/examples/config.shannon_example.yaml
  config/service_alias.go
  config/testdata/morse.example.yaml
  config/testdata/shannon.example.yaml
  e2e/morse.example.yaml
  e2e/shannon.example.yaml
  e2e/shannon_relay_test.go
  local/path/config/shannon.example.yaml
  makefiles/localnet.mk
Labels: documentation, tooling

#94 [PATCH] [READY] Fix `values.yaml` and small typo in makefile
  local/kubernetes/path-values.yaml
  makefiles/localnet.mk
Labels: bug

#95 Fix: make the /v1 endpoint more permissive
  README.md
  e2e/morse_relay_test.go
  e2e/shannon.example.yaml
  e2e/shannon_relay_test.go
  router/router.go
Labels: loadtest

#60 [ENVOY][TILT] feat: run whole PATH stack including Envoy using Tilt
  .github/workflows/upload-pages-artifact.yml
  .gitignore
  Makefile
  README.md
  Tiltfile
  cmd/.config.morse_example.yaml
  cmd/.config.morse_example_testnet.yaml
  cmd/.config.shannon_example.yaml
  cmd/main.go
  config/config_test.go
  config/examples/config.morse_example.yaml
  config/examples/config.shannon_example.yaml
  config/morse/gateway_config_test.go
  config/service_alias.go
  config/testdata/morse.example.yaml
  config/testdata/shannon.example.yaml
  docusaurus/README.md
  docusaurus/docs/README.md
  docusaurus/docs/develop/develop.md
  docusaurus/docs/develop/envoy/_category_.json
  docusaurus/docs/develop/envoy/introduction.md
  docusaurus/docs/develop/path/_category_.json
  docusaurus/docs/develop/path/introduction.md
  docusaurus/docs/operate/operate.md
  docusaurus/docusaurus.config.js
  e2e/docker_test.go
  e2e/scripts/update_shannon_config_from_secrets.sh
  e2e/shannon.example.yaml
  e2e/shannon_relay_test.go
  envoy/auth_server/auth/auth_handler.go
  envoy/auth_server/proto/gateway_endpoint.proto
  envoy/envoy.template.yaml
  envoy/ratelimit.yaml
  envoy/scripts/copy_envoy_config.sh
  envoy/scripts/copy_gateway_endpoints_yaml.sh
  local/kubernetes/envoy-ext-authz.yaml
  local/kubernetes/envoy-pads.yaml
  local/kubernetes/envoy-proxy.yaml
  local/kubernetes/envoy-ratelimit.yaml
  local/kubernetes/envoy-redis.yaml
  local/kubernetes/path-values.yaml
  local/path/config/morse.example.yaml
  local/path/config/shannon.example.yaml
  makefiles/localnet.mk
  protocol/morse/fullnode.go
Labels: enhancement, envoy

#101 Support using HTTP Headers to specify target service ID
  request/parser.go
Labels: enhancement

#100 [ENVOY][AUTH] feat: configurable endpoint id passing
  Makefile
  docusaurus/docs/README.md
  docusaurus/docs/develop/envoy/introduction.md
  docusaurus/docs/develop/path/introduction.md
  envoy/auth_server/.env.example
  envoy/auth_server/auth/auth_handler.go
  envoy/auth_server/auth/auth_handler_test.go
  envoy/auth_server/auth/endpoint_id_extractor.go
  envoy/auth_server/auth/endpoint_id_extractor_test.go
  envoy/auth_server/main.go
  envoy/envoy.template.yaml
  local/kubernetes/envoy-ext-authz.yaml
  makefiles/test_requests.mk
Labels: envoy, authorization

#103 [Morse Support] All Morse EVM IDs to `service_alias` map
  config/service_alias.go
Labels: enhancement, service

#82 [Workflows] Add `reviewdog` workflow and `PR` template
  .github/pull_request_template.md
  .github/workflows/reviewdog.yml
Labels: tooling

#107 [Test Fixes] Followup to #103 add Morse/Shannon/Service IDs
  Makefile
  cmd/qos.go
  config/service_alias.go
  e2e/docker_test.go
  e2e/morse_relay_test.go
Labels: bug, testing

#106 [QoS] Introduce v0 of Noop QoS module
  qos/noop/context.go
  qos/noop/http.go
  qos/noop/noop.go
  qos/noop/observation.go
  qos/noop/response.go
  qos/noop/selector.go
Labels: enhancement, qos

#110 fix: small changes to E2E tests to use header for passing service ID
  .gitignore
  Makefile
  config/config_test.go
  config/examples/config.morse_example.yaml
  config/examples/config.shannon_example.yaml
  config/service_alias.go
  e2e/morse_relay_test.go
  e2e/shannon_relay_test.go
Labels: bug, E2E

#111 [Docs] Add config location for Morse E2E tests
  Makefile
  docusaurus/docs/develop/path/introduction.md
Labels: documentation, E2E

#115 Fix: move COPY source to the bottom of the Dockerfile build instructions
  Dockerfile
Labels: code health

#113 [QoS] feat: expand support for NoOp functionality
  cmd/main.go
  cmd/qos.go
  config/config.go
  config/config.schema.yaml
  config/config_test.go
  config/examples/config.morse_example.yaml
  config/examples/config.shannon_example.yaml
  config/service_qos.go
  docusaurus/docs/develop/path/introduction.md
  makefiles/test_requests.mk
  protocol/morse/protocol.go
  protocol/shannon/protocol.go
  qos/noop/context.go
  request/errors.go
  request/parser.go
Labels: enhancement

#102 [ENVOY] feat: Envoy to set Service ID header from subdomain
  Makefile
  Tiltfile
  config/config.go
  config/config_test.go
  config/examples/config.shannon_example.yaml
  docusaurus/docs/develop/envoy/introduction.md
  docusaurus/docs/develop/path/introduction.md
  docusaurus/docs/operate/configs/_category_.json
  docusaurus/docs/operate/configs/envoy_config.md
  docusaurus/docusaurus.config.js
  docusaurus/package-lock.json
  docusaurus/package.json
  docusaurus/yarn.lock
  e2e/morse_relay_test.go
  e2e/shannon_relay_test.go
  envoy/allowed-services.template.lua
  envoy/auth_server/auth/auth_handler.go
  envoy/auth_server/auth/authorizer_jwt.go
  envoy/auth_server/auth/endpoint_id_extractor.go
  envoy/auth_server/auth/endpoint_id_extractor_test.go
  envoy/auth_server/endpoint_store/client_mock_test.go
  envoy/auth_server/endpoint_store/endpoint_store_test.go
  envoy/envoy.template.yaml
  envoy/ratelimit.template.yaml
  envoy/scripts/copy_envoy_config.sh
  envoy/scripts/copy_gateway_endpoints_yaml.sh
  local/kubernetes/envoy-ext-authz.yaml
  local/kubernetes/envoy-proxy.yaml
  makefiles/test_requests.mk
  request/parser.go
Labels: enhancement, envoy

#108 [ENVOY][AUTH] feat: Auth Server load config from YAML
  Tiltfile
  config/config.schema.yaml
  config/examples/config.morse_example.yaml
  config/examples/config.shannon_example.yaml
  docusaurus/docs/develop/envoy/introduction.md
  docusaurus/docs/develop/path/introduction.md
  envoy/auth_server/config/config.go
  envoy/auth_server/config/config_test.go
  envoy/auth_server/main.go
  envoy/envoy.template.yaml
  local/kubernetes/envoy-ext-authz.yaml
  protocol/shannon/mode_delegated.go
  router/router.go
Labels: envoy, authorization

#93 [Merge After #108] [DOCS] PATH cheatsheet
  .gitignore
  Makefile
  docusaurus/docs/develop/envoy/introduction.md
  docusaurus/docs/develop/path/cheatsheet.md
  docusaurus/docs/develop/path/introduction.md
  envoy/envoy.template.yaml
  envoy/scripts/copy_envoy_config.sh
  envoy/scripts/copy_gateway_endpoints_yaml.sh
  local/scripts/install_poktrolld_cli.sh
  local/scripts/install_tools.sh
  local/scripts/shannon_populate_config.sh
  makefiles/quickstart.mk
Labels: documentation
