Repository buildwithgrove/path, pull requests merged in 2024-09, with the labels that each got.

#8 chore: update package name
  Dockerfile
  README.md
  cmd/main.go
  config/config.go
  config/config_test.go
  config/morse/gateway_config.go
  config/morse/gateway_config_test.go
  config/morse/signed_aat.go
  config/shannon/gateway_config.go
  config/shannon/gateway_config_test.go
  config/user_data.go
  e2e/shannon_relay_test.go
  gateway/gateway.go
  gateway/qos.go
  gateway/request.go
  go.mod
  qos/evm/evm.go
  relayer/morse/app.go
  relayer/morse/endpoint.go
  relayer/morse/protocol.go
  relayer/relayer.go
  relayer/shannon/app.go
  relayer/shannon/endpoint.go
  relayer/shannon/fullnode.go
  relayer/shannon/protocol.go
  request/parser.go
  request/qos_names.go
  request/qos_provider.go
  router/router.go
  router/router_test.go
Labels: enhancement

#9 Add GitHub action go E2E test v0
  .github/workflows/run-e2e-tests.yml
  e2e/.example.test.yaml
  e2e/scripts/update_config_from_secrets.sh
Labels: infra

#21 fix: resolves panic when endpoint called for an unassigned service
  .gitignore
  config/config.go
  config/config.schema.yaml
  config/config_test.go
  request/errors.go
  request/parser.go
  request/qos_provider.go
Labels: bug

#25 chore: fix linter warnings
  gateway/gateway.go
  relayer/morse/protocol.go
  relayer/shannon/grpc.go
  relayer/shannon/protocol.go
  router/router_test.go
Labels: enhancement

#17 Infra: Docker images and status badges
  .github/workflows/main-build.yml
  .github/workflows/release-artifacts.yml
  .github/workflows/run-e2e-tests.yml
  .github/workflows/run-tests.yml
  .golangci.yml
  README.md
Labels: enhancement, infra

#15 feat: DB driver and cache
  Dockerfile
  Makefile
  README.md
  cmd/main.go
  config/config.go
  config/config_test.go
  config/testdata/morse.example.yaml
  config/testdata/shannon.example.yaml
  config/user_data.go
  config/user_data_test.go
  config/utils/utils.go
  docker-compose.yml
  envoy/auth_plugin/auth_plugin/db/cache.go
  envoy/auth_plugin/auth_plugin/db/cache_test.go
  envoy/auth_plugin/auth_plugin/db/driver.go
  envoy/auth_plugin/auth_plugin/db/driver_mock_test.go
  envoy/auth_plugin/auth_plugin/db/postgres/db.generated.go
  envoy/auth_plugin/auth_plugin/db/postgres/docker_test.go
  envoy/auth_plugin/auth_plugin/db/postgres/driver.go
  envoy/auth_plugin/auth_plugin/db/postgres/driver_test.go
  envoy/auth_plugin/auth_plugin/db/postgres/models.generated.go
  envoy/auth_plugin/auth_plugin/db/postgres/query.sql.generated.go
  envoy/auth_plugin/auth_plugin/db/postgres/sqlc/query.sql
  envoy/auth_plugin/auth_plugin/db/postgres/sqlc/schema.sql
  envoy/auth_plugin/auth_plugin/db/postgres/sqlc/sqlc.yaml
  envoy/auth_plugin/auth_plugin/db/postgres/testdata/seed-test-db.sql
  envoy/auth_plugin/auth_plugin/go.mod
  envoy/auth_plugin/auth_plugin/go.sum
  envoy/auth_plugin/auth_plugin/user/gateway_endpoint.go
  go.mod
  go.sum
  router/router.go
  router/router_mock_test.go
  router/router_test.go
Labels: enhancement

#20 feat: enhances e2e shannon relay test to a true E2E
  .github/workflows/release-artifacts.yml
  .gitignore
  Makefile
  cmd/main.go
  docker-compose.yml
  e2e/.example.test.yaml
  e2e/docker_test.go
  e2e/shannon_relay_test.go
  envoy/auth_plugin/db/cache.go
  envoy/auth_plugin/db/cache_test.go
  envoy/auth_plugin/db/driver.go
  envoy/auth_plugin/db/driver_mock_test.go
  envoy/auth_plugin/db/postgres/db.generated.go
  envoy/auth_plugin/db/postgres/docker_test.go
  envoy/auth_plugin/db/postgres/driver.go
  envoy/auth_plugin/db/postgres/driver_test.go
  envoy/auth_plugin/db/postgres/models.generated.go
  envoy/auth_plugin/db/postgres/query.sql.generated.go
  envoy/auth_plugin/db/postgres/sqlc/query.sql
  envoy/auth_plugin/db/postgres/sqlc/schema.sql
  envoy/auth_plugin/db/postgres/sqlc/sqlc.yaml
  envoy/auth_plugin/db/postgres/testdata/seed-test-db.sql
  envoy/auth_plugin/go.mod
  envoy/auth_plugin/go.sum
  envoy/auth_plugin/user/gateway_endpoint.go
  go.mod
  go.sum
  health/checker.go
  relayer/morse/protocol.go
  relayer/relayer.go
  relayer/shannon/protocol.go
  router/router.go
  router/router_test.go
Labels: enhancement

#37 Add `workflow_dispatch` trigger to be able to run workflows manually
  .github/workflows/main-build.yml
  .github/workflows/release-artifacts.yml
  .github/workflows/run-tests.yml
Labels: infra

#34 [Docker] Update the tag of the built and published docker images
  .github/workflows/main-build.yml
Labels: infra
