Repository buildwithgrove/path, pull requests merged in 2024-11, with the labels that each got.

#57 [CHORE][CONFIG] chore: update config yaml schema
  .gitignore
  config/config.schema.yaml
Labels: code health

#53 [QoS] Implement QoS checks for Solana v0
  cmd/qos.go
  e2e/morse_relay_test.go
  qos/evm/response.go
  qos/evm/response_generic.go
  qos/jsonrpc/response.go
  qos/jsonrpc/response_error.go
  qos/solana/check.go
  qos/solana/context.go
  qos/solana/endpoint.go
  qos/solana/http.go
  qos/solana/methods.go
  qos/solana/observe.go
  qos/solana/request.go
  qos/solana/response.go
  qos/solana/response_generic.go
  qos/solana/response_getepochinfo.go
  qos/solana/response_gethealth.go
  qos/solana/solana.go
  qos/solana/state.go
  qos/solana/store.go
  relayer/protocol.go
  relayer/shannon/fullnode_cache.go
  relayer/shannon/fullnode_lazy.go
Labels: qos, solana

#63 [Infra] Fix workflow condition for manual trigger
  .github/workflows/main-build.yml
  cmd/qos.go
  e2e/shannon.example.yaml
  qos/evm/observe.go
  qos/evm/store.go
Labels: infra

#64 Update README.md w/ reference to Gateway Server
  README.md
Labels: documentation

#65 fix: update 0021 to F00C and eth-mainnet to eth
  Makefile
  README.md
  cmd/.config.morse_example.yaml
  cmd/.config.morse_example_testnet.yaml
  cmd/.config.shannon_example.yaml
  cmd/qos.go
  config/config.go
  config/config_test.go
  config/service.go
  config/testdata/morse.example.yaml
  docusaurus/docs/README.md
  e2e/morse.example.yaml
  e2e/morse_relay_test.go
  e2e/shannon.example.yaml
  request/parser.go
Labels: bug

#66 [PATCH][READY] Added update_docs target
  .github/workflows/upload-pages-artifact.yml
  Makefile
Labels: documentation

#69 Fix docs workflow
  .github/workflows/upload-pages-artifact.yml
  README.md
  docusaurus/docs/README.md
Labels: documentation

#70 [Config] Revamp Shannon config example
  cmd/.config.shannon_example.yaml
  config/config.schema.yaml
  config/config_test.go
  config/testdata/shannon.example.yaml
  e2e/scripts/update_shannon_config_from_secrets.sh
  e2e/shannon.example.yaml
  protocol/shannon/config.go
Labels: gateway

#68 fix: update service QoS mapping file
  .gitignore
  cmd/qos.go
  config/service.go
  config/service_alias.go
Labels: service
