Repository buildwithgrove/path, pull requests merged in 2025-08, with the labels that each got.

#372 [Code Health] Remove Morse protocol code and references
  .github/ISSUE_TEMPLATE/improve_docs.md
  .gitignore
  .markdownlint.json
  .serena/memories/metrics_patterns.md
  .serena/memories/project_overview.md
  .serena/memories/task_completion_checklist.md
  CLAUDE.md
  Makefile
  cmd/main.go
  cmd/morse.go
  config/config.go
  config/config.schema.yaml
  config/config_test.go
  config/morse/gateway_config.go
  config/morse/gateway_config_test.go
  config/morse/signed_aat.go
  config/morse/signed_aat_test.go
  config/service_qos_config.go
  data/legacy.go
  data/legacy_protocol_morse.go
  data/legacy_protocol_shannon.go
  docusaurus/scripts/service_qos_doc_generator.sh
  e2e/config/e2e_load_test.config.tmpl.yaml
  e2e/config/services.schema.yaml
  e2e/config_test.go
  e2e/main_test.go
  e2e/service_test.go
  gateway/gateway.go
  gateway/protocol.go
  go.mod
  go.sum
  makefiles/configs.mk
  makefiles/test_requests.mk
  metrics/protocol/morse/metrics.go
  metrics/protocol/protocol.go
  observation/protocol/morse.pb.go
  observation/protocol/observations.pb.go
  observation/qos/evm.pb.go
  proto/path/protocol/morse.proto
  proto/path/protocol/observations.proto
  proto/path/qos/evm.proto
  protocol/crypto/keys.go
  protocol/endpoint.go
  protocol/morse/app.go
  protocol/morse/context.go
  protocol/morse/endpoint.go
  protocol/morse/errors.go
  protocol/morse/fullnode.go
  protocol/morse/gateway_mode.go
  protocol/morse/log.go
  protocol/morse/observation.go
  protocol/morse/protocol.go
  protocol/morse/sanction.go
  protocol/morse/sanctioned_endpoints_store.go
  protocol/service.go
  protocol/shannon/context.go
  protocol/shannon/observation.go
Labels: code health

#389 [Session Rollovers] Simplify & Consolidate Timeouts
  config/config_test.go
  config/router.go
  config/router_test.go
  data/reporter_http.go
  gateway/gateway.go
  gateway/request_context.go
  gateway/request_context_handle_request.go
  observation/protocol/shannon.pb.go
  proto/path/protocol/shannon.proto
  protocol/payload.go
  protocol/shannon/context.go
  protocol/shannon/errors.go
  protocol/shannon/http_client.go
  protocol/shannon/log.go
  protocol/shannon/sanctions.go
  qos/cosmos/request_validator_jsonrpc.go
  qos/cosmos/request_validator_rest.go
  qos/evm/context.go
  qos/noop/context.go
  qos/noop/noop.go
  qos/solana/context.go
  router/router.go
Labels: code health

#395 [QoS][Cosmos][Fallback] add RPC-type specific configuration for service fallback config
  .github/workflows/run-e2e-tests.yml
  config/config.schema.yaml
  config/config_test.go
  config/examples/config.shannon_example.yaml
  docusaurus/docs/develop/path/5_load_tests_quickstart.md
  e2e/config/e2e_load_test.config.schema.yaml
  e2e/config/e2e_load_test.config.tmpl.yaml
  e2e/config_test.go
  e2e/docker_test.go
  e2e/scripts/ci/set_docker_log.sh
  e2e/scripts/ci/update_shannon_config_from_secrets.sh
  e2e/scripts/run_eth_fallback_test.sh
  makefiles/test.mk
  metrics/protocol/shannon/metrics.go
  protocol/shannon/config.go
  protocol/shannon/context.go
  protocol/shannon/endpoint.go
  protocol/shannon/http_client.go
  protocol/shannon/log.go
  protocol/shannon/observation.go
  protocol/shannon/protocol.go
  protocol/shannon/sanctioned_endpoints_store.go
  websockets/bridge.go
  websockets/bridge_test.go
  websockets/connection_test.go
Labels: qos, Comet/Cosmos

#398 [Scripts] Add scripts to curl endpoints
  local/scripts/curl_abci_info_monitor.sh
  local/scripts/curl_load_test_session_rollover.sh
Labels: protocol, Scripts

#402 [Review] Post-merge review of #396
  gateway/protocol.go
  gateway/request_context.go
  protocol/shannon/config.go
  protocol/shannon/context.go
  protocol/shannon/endpoint.go
  protocol/shannon/protocol.go
  websockets/bridge.go
  websockets/bridge_test.go
Labels: review

#413 [QoS][Solana][Observability] Fix: qos solana endpoint 500 status observations
  observation/qos/solana.pb.go
  observation/qos/solana_interpreter.go
  proto/path/qos/solana.proto
  qos/solana/response_generic.go
  qos/solana/response_getepochinfo.go
  qos/solana/response_gethealth.go
Labels: qos, solana, observability

#411 [Docs] fix: PATH configs links
  docusaurus/docs/operate/getting_started/1_quickstart.md
  local/Dockerfile.dev
  local/scripts/localnet.sh
Labels: documentation

#423 [HTTP] Introduce Buffer Pool & HTTP/gRPC TECHDEBT
  config/config_test.go
  config/shannon/gateway_config_test.go
  gateway/errors.go
  gateway/http_request_context.go
  gateway/qos.go
  gateway/request.go
  makefiles/release.mk
  metrics/protocol/shannon/metrics.go
  network/concurrency/buffer_pool.go
  network/concurrency/buffer_pool_test.go
  network/concurrency/concurrency_limiter.go
  network/concurrency/concurrency_limiter_test.go
  network/grpc/grpc.go
  network/grpc/grpc_test.go
  network/http/errors.go
  network/http/http.go
  network/http/http_client.go
  protocol/shannon/config.go
  protocol/shannon/context.go
  protocol/shannon/errors.go
  protocol/shannon/fullnode_lazy.go
  protocol/shannon/grpc.go
  protocol/shannon/protocol.go
  protocol/shannon/sanctions.go
  qos/cosmos/context.go
  qos/cosmos/error_context.go
  qos/cosmos/http.go
  qos/cosmos/request_validator_jsonrpc.go
  qos/cosmos/request_validator_rest.go
  qos/cosmos/response_cometbft_health.go
  qos/cosmos/response_cometbft_status.go
  qos/cosmos/response_cosmos_status.go
  qos/cosmos/response_evm_chainid.go
  qos/cosmos/response_jsonrpc_unrecognized.go
  qos/cosmos/response_rest_unrecognized.go
  qos/error_context.go
  qos/evm/context.go
  qos/evm/error_context.go
  qos/evm/http.go
  qos/http.go
  qos/noop/context.go
  qos/noop/http.go
  qos/solana/context.go
  request/parser.go
Labels: gateway

#414 [Error Capture] Account for a code path that should never happen in `sendProtocolRelay`
  protocol/shannon/context.go
Labels: bug
