Repository buildwithgrove/path, pull requests merged in 2025-01, with the labels that each got.

#123 Adding link to Discord to README.md and instructions for Technical Support
  README.md
  docusaurus/docs/operate/operate.md
  docusaurus/docusaurus.config.js
Labels: documentation, off-chain

#122 fix: small tweaks to improve localnet dev experience
  Tiltfile
  envoy/envoy.template.yaml
  local/kubernetes/path-values.yaml
  router/router.go
Labels: devex

#119 [Documentation] chore: cleanup and improve documentation
  Makefile
  Tiltfile
  config/config.schema.yaml
  config/examples/config.shannon_example.yaml
  config/router.go
  docusaurus/docs/README.md
  docusaurus/docs/develop/envoy/_category_.json
  docusaurus/docs/develop/envoy/envoy_config.md
  docusaurus/docs/develop/envoy/walkthrough.md
  docusaurus/docs/develop/pads/_category_.json
  docusaurus/docs/develop/pads/endpoint_configuration.md
  docusaurus/docs/develop/pads/interface_definition.md
  docusaurus/docs/develop/pads/introduction.md
  docusaurus/docs/develop/pads/postgres.md
  docusaurus/docs/develop/pads/yaml.md
  docusaurus/docs/develop/path/_category_.json
  docusaurus/docs/develop/path/cheatsheet.md
  docusaurus/docs/develop/path/introduction.md
  docusaurus/docs/develop/path/path_config.md
  docusaurus/docs/develop/path/walkthrough.md
  docusaurus/docs/operate/configs/_category_.json
  e2e/docker_test.go
  envoy/envoy.template.yaml
  envoy/scripts/copy_gateway_endpoints_yaml.sh
  local/kubernetes/envoy-proxy.yaml
  local/kubernetes/path-values.yaml
  local/scripts/shannon_populate_config.sh
  makefiles/test_requests.mk
  protocol/shannon/mode_delegated.go
Labels: documentation

#130 fix: update the jsonrpc.Response struct to adhere to the JSONRPC spec
  qos/jsonrpc/response.go
  qos/jsonrpc/response_error.go
  qos/jsonrpc/response_test.go
  qos/solana/response_getepochinfo.go
  qos/solana/response_gethealth.go
Labels: enhancement, qos

#133 fix: bug fix from json rpc response struct field types
  qos/jsonrpc/response.go
Labels: bug

#118 [Config] Add logger config
  cmd/main.go
  config/config.go
  config/config.schema.yaml
  config/config_test.go
  config/examples/config.morse_example.yaml
  config/examples/config.shannon_example.yaml
  config/logger.go
  docusaurus/docs/develop/path/path_config.md
Labels: code health, devex

#132 chore: minor docs fixes
  docusaurus/docs/develop/envoy/walkthrough.md
  docusaurus/docs/develop/path/cheatsheet.md
  docusaurus/docs/develop/path/path_config.md
Labels: documentation

#136 Add issue template for improving documentation
  docs/.github/ISSUE_TEMPLATE/improve_docs.md
Labels: documentation, devex

#140 [Protocol] Correct the scope of onchain app queries made by Shannon protocol instance
  cmd/main.go
  cmd/shannon.go
  config/config.schema.yaml
  go.mod
  go.sum
  protocol/shannon/fullnode_cache.go
  protocol/shannon/fullnode_lazy.go
  protocol/shannon/gateway_mode.go
  protocol/shannon/mode_centralized.go
  protocol/shannon/mode_delegated.go
  protocol/shannon/protocol.go
Labels: protocol, shannon

#137 [Docs] Refactoring the `PATH` Developer Guide docs
  .github/workflows/run-tests.yml
  Makefile
  cmd/main.go
  config/config.schema.yaml
  config/config_test.go
  config/examples/config.shannon_example.yaml
  docusaurus/docs/README.md
  docusaurus/docs/develop/envoy/walkthrough.md
  docusaurus/docs/develop/path/cheat_sheet_morse.md
  docusaurus/docs/develop/path/cheat_sheet_shannon.md
  docusaurus/docs/develop/path/cheatsheet.md
  docusaurus/docs/develop/path/env_setup.md
  docusaurus/docs/develop/path/introduction.md
  docusaurus/docs/develop/path/path_config.md
  docusaurus/docs/develop/path/walkthrough.md
  docusaurus/docs/operate/operate.md
  envoy/auth_server/auth/endpoint_id_extractor.go
  envoy/auth_server/main.go
  envoy/envoy.template.yaml
  local/scripts/install_poktrolld_cli.sh
  local/scripts/shannon_populate_config.sh
  makefiles/configs.mk
  makefiles/deps.mk
  makefiles/docs.mk
  makefiles/envoy.mk
  makefiles/localnet.mk
  makefiles/morse_configs.mk
  makefiles/shannon_configs.mk
  makefiles/test.mk
  makefiles/test_requests.mk
  protocol/shannon/config.go
Labels: documentation

#134 [Merge after #127] [QoS] Ensure returned id fields match request
  e2e/morse_relay_test.go
  e2e/shannon_relay_test.go
  gateway/request_context.go
  qos/evm/response.go
  qos/jsonrpc/id.go
  qos/jsonrpc/response.go
  qos/jsonrpc/response_test.go
  qos/solana/response.go
Labels: enhancement, qos

#127 [QoS][Adoption] config EVM chain IDs
  cmd/main.go
  cmd/qos.go
  config/service_qos.go
  e2e/morse_relay_test.go
  e2e/shannon_relay_test.go
  gateway/request_context.go
  qos/evm/new.go
  qos/evm/response.go
  qos/jsonrpc/id.go
  qos/jsonrpc/response.go
  qos/jsonrpc/response_test.go
  qos/solana/response.go
Labels: enhancement, qos

#139 [QoS] feat: introduce worker pool concurrency for QoS hydrator
  cmd/hydrator.go
  config/config.go
  config/config.schema.yaml
  config/hydrator.go
  docusaurus/docs/develop/path/path_config.md
  gateway/hydrator.go
Labels: qos

#148 [Workflows] Update GitHub actions from v3 to v4
  .github/workflows/main-build.yml
  .github/workflows/upload-pages-artifact.yml
Labels: bug

#151 [docs] fix typo in PATH config
  docusaurus/docs/develop/path/path_config.md
Labels: documentation

#150 [Docs] Adding diagrams to main page of path.grove.city
  docusaurus/docs/README.md
Labels: documentation

#135 [WebSockets] Websocket override URLs
  cmd/main.go
  config/config.schema.yaml
  config/config_test.go
  config/examples/config.morse_example.yaml
  config/examples/config.shannon_example.yaml
  config/shannon/gateway_config.go
  docusaurus/docs/develop/path/path_config.md
  envoy/envoy.template.yaml
  gateway/gateway.go
  gateway/protocol.go
  gateway/qos.go
  gateway/request_context.go
  gateway/request_type.go
  go.mod
  go.sum
  protocol/morse/context.go
  protocol/shannon/context.go
  qos/evm/evm.go
  qos/noop/noop.go
  qos/solana/solana.go
  router/router.go
  router/router_mock_test.go
  router/router_test.go
  websockets/bridge.go
  websockets/bridge_test.go
  websockets/connection.go
  websockets/connection_test.go
Labels: websockets

#131 [Observability] Add PATH dashboard with OS-level metrics to local development environment.
  Makefile
  Tiltfile
  local/grafana-dashboards/path.json
  makefiles/localnet.mk
Labels: observability

#145 [QoS][REST] REST NoOp implementation
  docusaurus/docs/develop/path/qos.md
  envoy/envoy.template.yaml
  qos/noop/context.go
  qos/noop/noop.go
  qos/noop/selector.go
  router/router.go
  router/router_test.go
Labels: enhancement, qos, rest

#153 Add feedback issue template
  docs/.github/ISSUE_TEMPLATE/feedback.md
Labels: documentation
