Repository buildwithgrove/path, pull requests merged in 2025-04, with the labels that each got.

#196 [Bug][QoS] Fix race condition in hydrator by creating a new request context per request to ensure correct endpoint selection and observation application.
  gateway/hydrator.go
  gateway/protocol.go
  gateway/qos.go
  protocol/morse/protocol.go
  protocol/shannon/context.go
  protocol/shannon/mode_centralized.go
  protocol/shannon/protocol.go
  qos/cometbft/check.go
  qos/cometbft/context.go
  qos/evm/check.go
  qos/evm/context.go
  qos/solana/check.go
  qos/solana/context.go
Labels: bug, qos

#197 [QoS][REFACTOR] Implement TODO_REFACTOR to unify protocol interface across gateway and hydrator
  gateway/hydrator.go
  gateway/protocol.go
  gateway/request_context.go
  protocol/endpoint.go
  protocol/morse/context.go
  protocol/morse/protocol.go
  protocol/shannon/context.go
  protocol/shannon/gateway_mode.go
  protocol/shannon/mode_delegated.go
  protocol/shannon/protocol.go
  qos/cometbft/context.go
  qos/cometbft/observe.go
  qos/cometbft/store.go
  qos/evm/context.go
  qos/evm/error_context.go
  qos/evm/observe.go
  qos/evm/store.go
  qos/noop/selector.go
  qos/solana/context.go
  qos/solana/observe.go
  qos/solana/store.go
Labels: enhancement, code health

#201 [Bug] Fix broken hydrator observations
  gateway/hydrator.go
Labels: bug

#194 [QoS][Config] feat: add EVM archival check and rework config service QoS file
  Makefile
  cmd/main.go
  cmd/qos.go
  config/service_qos.go
  config/service_qos_config.go
  docusaurus/docs/learn/qos/_category_.json
  docusaurus/docs/learn/qos/evm_archival.md
  docusaurus/docusaurus.config.js
  docusaurus/package-lock.json
  docusaurus/package.json
  docusaurus/sidebars.js
  docusaurus/yarn.lock
  gateway/qos.go
  go.mod
  go.sum
  makefiles/docs.mk
  observation/gateway.pb.go
  observation/http.pb.go
  observation/metadata/metadata.pb.go
  observation/observations.pb.go
  observation/protocol/morse.pb.go
  observation/protocol/observations.pb.go
  observation/protocol/shannon.pb.go
  observation/qos/cometbft.pb.go
  observation/qos/evm.pb.go
  observation/qos/evm_response_interpreters.go
  observation/qos/jsonrpc.pb.go
  observation/qos/observations.pb.go
  observation/qos/solana.pb.go
  proto/path/qos/evm.proto
  protocol/morse/app.go
  protocol/morse/endpoint.go
  protocol/morse/log.go
  qos/cometbft/qos.go
  qos/cometbft/service_qos_config.go
  qos/evm/check.go
  qos/evm/context.go
  qos/evm/endpoint.go
  qos/evm/evm.go
  qos/evm/methods.go
  qos/evm/observe.go
  qos/evm/qos.go
  qos/evm/request_validator.go
  qos/evm/response.go
  qos/evm/response_getbalance.go
  qos/evm/service_qos_config.go
  qos/evm/state.go
  qos/evm/state_archival.go
  qos/evm/store.go
  qos/jsonrpc/request.go
  qos/solana/qos.go
  qos/solana/service_qos_config.go
Labels: qos

#195 [READY BUT DO NOT MEGE YET][Shannon Dependencies] Update `shannon-sdk` and `poktroll` dependencies
  go.mod
  go.sum
Labels: protocol

#198 [QoS] Account for `TLS` and `non-JSON` errors in `Morse` QoS logic
  observation/protocol/morse.pb.go
  proto/path/protocol/morse.proto
  protocol/morse/errors.go
  protocol/morse/observation.go
Labels: qos

#209 [Docs] Poor Man's RAG using Claude
  .claudeignore
  .claudeignore_docs
  Makefile
  docusaurus/docs/develop/tips/claude.md
  makefiles/claude.mk
Labels: tooling, ai

#211 [docs] Fix embedded helm chart docs to point to main branch of helm repo
  docusaurus/docs/operate/helm/3_guard.md
  docusaurus/docs/operate/helm/5_values.md
Labels: documentation

#205 [Testing] Add EVM E2E load test using Vegeta
  .github/workflows/run-tests.yml
  .gitignore
  config/examples/config.morse_example.yaml
  config/service_qos_config.go
  docusaurus/docs/develop/path/7_e2e_tests.md
  docusaurus/docs/operate/getting_started/1_support.md
  docusaurus/docs/operate/getting_started/2_releases.md
  docusaurus/docs/operate/getting_started/_category_.json
  e2e/docker_test.go
  e2e/evm_methods_test.go
  e2e/evm_test.go
  e2e/morse_relay_test.go
  e2e/opts_test.go
  e2e/scripts/update_morse_config_from_secrets.sh
  e2e/shannon_relay_test.go
  e2e/vegeta_test.go
  go.mod
  go.sum
  makefiles/configs_shannon.mk
  makefiles/test.mk
  observation/gateway.pb.go
  observation/http.pb.go
  observation/metadata/metadata.pb.go
  observation/observations.pb.go
  observation/protocol/morse.pb.go
  observation/protocol/observations.pb.go
  observation/protocol/shannon.pb.go
  observation/qos/cometbft.pb.go
  observation/qos/evm.pb.go
  observation/qos/jsonrpc.pb.go
  observation/qos/observations.pb.go
  observation/qos/solana.pb.go
  qos/evm/service_qos_config.go
  qos/evm/store.go
  qos/jsonrpc/request.go
Labels: testing

#200 [QoS] Refactor QoS checks and add expiry & allowance
  Tiltfile
  docusaurus/docs/develop/helm/_category_.json
  docusaurus/docs/develop/helm/guard.md
  docusaurus/docs/develop/helm/path.md
  docusaurus/docs/develop/helm/values.md
  docusaurus/docs/develop/helm/watch.md
  docusaurus/docs/develop/path/5_configurations_path.md
  docusaurus/docs/operate/1_operate.md
  docusaurus/docs/operate/2_releases.md
  e2e/scripts/update_morse_config_from_secrets.sh
  e2e/scripts/update_shannon_config_from_secrets.sh
  gateway/hydrator.go
  qos/evm/check.go
  qos/evm/check_archival.go
  qos/evm/check_blocknumber.go
  qos/evm/check_chainid.go
  qos/evm/endpoint.go
  qos/evm/evm.go
  qos/evm/methods.go
  qos/evm/observe.go
  qos/evm/qos.go
  qos/evm/service_qos_config.go
  qos/evm/state.go
  qos/evm/state_archival.go
  qos/evm/store.go
Labels: qos

#213 feat: Add request processing timeout to prevent empty responses
  cmd/main.go
  config/config_test.go
  config/router.go
  config/router_test.go
  config/timeout.go
  gateway/gateway.go
  gateway/hydrator.go
  gateway/protocol.go
  gateway/request_context.go
  go.mod
  go.sum
  protocol/morse/protocol.go
  protocol/morse/sanction.go
  protocol/shannon/context.go
  protocol/shannon/fullnode_lazy.go
  protocol/shannon/gateway_mode.go
  protocol/shannon/mode_delegated.go
  protocol/shannon/protocol.go
  router/router.go
Labels: enhancement, protocol, shannon

#206 [QoS] Implement TODO to switch endpoint store to a field on service state
  docusaurus/docs/develop/path/7_e2e_tests.md
  docusaurus/docs/develop/path/img/9000.png
  qos/evm/check_archival.go
  qos/evm/check_blocknumber.go
  qos/evm/check_chainid.go
  qos/evm/context.go
  qos/evm/endpoint.go
  qos/evm/endpoint_selection.go
  qos/evm/endpoint_store.go
  qos/evm/evm.go
  qos/evm/qos.go
  qos/evm/request_validator.go
  qos/evm/service_state.go
  qos/evm/state.go
  qos/evm/store.go
  qos/jsonrpc/request.go
Labels: qos, code health

#215 [DATA] Export data to the legacy data pipeline
  cmd/data.go
  cmd/hydrator.go
  cmd/main.go
  config/config.go
  config/config.schema.yaml
  config/data_reporter.go
  data/legacy.go
  data/legacy_gateway.go
  data/legacy_protocol.go
  data/legacy_qos.go
  data/record.go
  data/reporter_http.go
  gateway/gateway.go
  gateway/hydrator.go
  gateway/observation.go
  gateway/request_context.go
  observation/auth.pb.go
  observation/gateway.pb.go
  observation/http.pb.go
  observation/protocol/morse.pb.go
  observation/qos/evm.pb.go
  proto/path/auth.proto
  proto/path/gateway.proto
  proto/path/http.proto
  proto/path/protocol/morse.proto
  proto/path/protocol/observations.proto
  proto/path/qos/evm.proto
  protocol/morse/context.go
  protocol/morse/errors.go
  protocol/morse/log.go
  protocol/morse/observation.go
  protocol/morse/protocol.go
  qos/evm/context.go
  qos/evm/request_validator.go
Labels: enhancement, data

#218 [Documentation][Devex] Improve clarity of install documentation and scripts for easier onboarding
  config/service_qos_config.go
  docusaurus/docs/develop/path/2_environment.md
  docusaurus/docs/develop/path/3_cheatsheet_shannon.md
  docusaurus/docs/operate/1_operate.md
  docusaurus/docs/operate/2_releases.md
  docusaurus/docs/operate/helm/1_introduction.md
  local/scripts/install_optional_tools.sh
  local/scripts/install_pocketd_cli.sh
  local/scripts/install_tools.sh
  makefiles/deps.mk
Labels: documentation, devex

#222 [QoS][Bug] Use correct EVM chain ID for anvil and fix docs autogen script
  config/service_qos_config.go
  docusaurus/docs/learn/qos/1_supported_services.md
  docusaurus/scripts/service_qos_doc_generator.sh
  makefiles/docs.mk
Labels: bug, qos

#224 [Metrics] Fix metrics cardinality
  .github/pull_request_template.md
  Makefile
  Tiltfile
  makefiles/localnet.mk
  makefiles/test.mk
  makefiles/test_requests.mk
  metrics/protocol/morse/metrics.go
Labels: metrics

#231 [CI] build image on merge to main branch
  .github/workflows/main-build.yml
Labels: CI

#233 [CI] Build image on main - remove redundant check
  .github/workflows/main-build.yml
Labels: CI

#227 Address review comments of PR #215
  config/config.schema.yaml
  config/data_reporter.go
  data/legacy.go
  data/legacy_gateway.go
  data/reporter_http.go
  gateway/observation.go
  observation/auth.pb.go
  observation/qos/evm.pb.go
  proto/path/auth.proto
  proto/path/qos/evm.proto
  qos/evm/context.go
Labels: code health

#232 [Protocol][Morse] feat: Expand endpoint error types for improved success rate
  observation/protocol/morse.pb.go
  proto/path/protocol/morse.proto
  protocol/morse/errors.go
  protocol/morse/observation.go
Labels: qos, morse

#221 [Testing][review] E2E Vegeta EVM Tests Review of #205
  .github/workflows/run-e2e-tests.yml
  .github/workflows/run-lint-and-test.yml
  .markdownlint.json
  config/examples/config.shannon_example.yaml
  docusaurus/docs/develop/path/3_cheatsheet_shannon.md
  docusaurus/docs/develop/path/7_e2e_tests.md
  docusaurus/docs/operate/helm/1_introduction.md
  docusaurus/package.json
  docusaurus/static/img/e2e_test.gif
  docusaurus/yarn.lock
  e2e/ciutil.go
  e2e/docker_test.go
  e2e/evm_methods_test.go
  e2e/evm_test.go
  e2e/opts_test.go
  e2e/vegeta_test.go
  makefiles/configs_morse.mk
  makefiles/configs_shannon.mk
  makefiles/test.mk
  protocol/shannon/protocol.go
  qos/cometbft/store.go
  qos/evm/endpoint_selection.go
  qos/jsonrpc/request.go
  qos/solana/store.go
Labels: documentation, code health, testing

#214 Add a Quick Start guide for operators
  docusaurus/docs/operate/Getting Started/1_quickstart.md
  docusaurus/docs/operate/Getting Started/2_support.md
  docusaurus/docs/operate/Getting Started/3_releases.md
Labels: documentation

#229 [Shannon][Protocol] Create simple caching layer for full node - without cache warmup
  cmd/shannon.go
  config/examples/config.shannon_example.yaml
  docusaurus/docs/develop/path/5_configurations_path.md
  e2e/evm_methods_test.go
  e2e/scripts/update_shannon_config_from_secrets.sh
  protocol/shannon/config.go
  protocol/shannon/fullnode_cache.go
  protocol/shannon/fullnode_lazy.go
  protocol/shannon/protocol.go
Labels: protocol, shannon, migration

#226 [Migration] Add F-chains to Shannon config and update script & docs
  config/service_qos_config.go
  docusaurus/docs/learn/qos/1_supported_services.md
  docusaurus/scripts/service_qos_doc_generator.sh
Labels: documentation, migration

#244 [Logs] Add verbosity to logging to read them in Grafana
  gateway/protocol.go
  metrics/qos/evm/metrics.go
  metrics/qos/qos.go
  observation/qos/evm.pb.go
  observation/qos/evm_interpreter.go
  proto/path/qos/evm.proto
  protocol/endpoint.go
  protocol/morse/protocol.go
  protocol/shannon/protocol.go
  qos/cometbft/context.go
  qos/cometbft/store.go
  qos/evm/context.go
  qos/evm/endpoint_selection.go
  qos/evm/error_context.go
  qos/evm/qos.go
  qos/evm/service_state.go
  qos/noop/selector.go
  qos/solana/context.go
  qos/solana/store.go
Labels: observability
