Repository buildwithgrove/path, pull requests merged in 2025-06, with the labels that each got.

#279 [Deps] Update Shannon SDK
  go.mod
  go.sum
Labels: dependencies

#280 [OPTIMISM][E2E] Correcting service id for `optimism` -> `op`
  e2e/config/services_shannon.yaml
Labels: bug, testing, shannon, e2e

#281 Fix: update protocol observations returns after update
  gateway/request_context.go
Labels: bug, protocol, observability

#278 [Shannon][Migration][Protocol] Update caching full node to use SturdyC including early refresh
  .gitignore
  go.mod
  go.sum
  protocol/shannon/fullnode_cache.go
  protocol/shannon/sanctioned_endpoints_store.go
Labels: protocol, shannon

#268 [QoS][Devtools] Add /disqualified_endpoints URL PATH to router and add OpenAPI spec
  Makefile
  api/path_openapi.yaml
  cmd/hydrator.go
  cmd/main.go
  cmd/qos.go
  docusaurus/docs/develop/tips/1_devtools.md
  docusaurus/docs/develop/tips/2_relay_util.md
  docusaurus/docs/develop/tips/3_claude.md
  docusaurus/docs/develop/tips/4_troubleshooting_faq.md
  docusaurus/docs/learn/api/1-handle-service-request.api.mdx
  docusaurus/docs/learn/api/2-health-check.api.mdx
  docusaurus/docs/learn/api/3-disqualified-endpoints.api.mdx
  docusaurus/docs/learn/api/path-path-api-toolkit-harness.info.mdx
  docusaurus/docs/learn/api/sidebar.ts
  docusaurus/docs/learn/qos/1_supported_services.md
  docusaurus/docusaurus.config.js
  docusaurus/package.json
  docusaurus/yarn.lock
  e2e/config/e2e_load_test.config.schema.yaml
  e2e/config/e2e_load_test.config.tmpl.yaml
  e2e/config_test.go
  e2e/main_test.go
  e2e/scripts/shannon-preliminary-services-test.sh
  gateway/protocol.go
  gateway/qos.go
  go.sum
  makefiles/devtools.mk
  makefiles/docs.mk
  metrics/devtools/disqualified_endpoint_reporter.go
  metrics/devtools/disqualified_endpoint_response.go
  protocol/morse/protocol.go
  protocol/shannon/errors.go
  protocol/shannon/protocol.go
  protocol/shannon/relay.go
  protocol/shannon/sanction.go
  protocol/shannon/sanctioned_endpoints_store.go
  qos/cometbft/cometbft.go
  qos/evm/check_archival.go
  qos/evm/endpoint_selection.go
  qos/evm/qos.go
  qos/evm/service_state.go
  qos/evm/state_archival.go
  qos/noop/noop.go
  qos/solana/solana.go
  router/router.go
  router/router_mock_test.go
  router/router_test.go
Labels: qos, devex

#293 [Shannon] Make OwnedApps a map to avoid excess looping calls to GetSession
  cmd/shannon.go
  protocol/shannon/fullnode_cache.go
  protocol/shannon/mode_centralized.go
  protocol/shannon/protocol.go
Labels: shannon

#300 [Load Test] Add pocket-beta1-5 services to load tests
  e2e/config/services_shannon.yaml
Labels: enhancement, loadtest

#298 [Review] Review of #292 which moved from GetApps to GetSessions
  cmd/shannon.go
  config/examples/config.shannon_example.yaml
  go.mod
  makefiles/proto.mk
  observation/protocol/shannon.pb.go
  proto/path/protocol/shannon.proto
  protocol/shannon/config.go
  protocol/shannon/errors.go
  protocol/shannon/fullnode_account_fetcher.go
  protocol/shannon/fullnode_cache.go
  protocol/shannon/gateway_mode.go
  protocol/shannon/mode_centralized.go
  protocol/shannon/mode_delegated.go
  protocol/shannon/observation.go
  protocol/shannon/protocol.go
Labels: code health

#301 [Protocol][Shannon] Shannon handles endpoint errors on relay response validation
  go.mod
  go.sum
  observation/protocol/shannon.pb.go
  proto/path/protocol/shannon.proto
  protocol/shannon/fullnode_cache.go
  protocol/shannon/sanctions.go
Labels: enhancement, protocol, shannon

#303 [E2E & Load Testing] Service Names - Aligning for consistency
  api/path_openapi.yaml
  docusaurus/docs/learn/qos/1_supported_services.md
  e2e/scripts/shannon_preliminary_services_helpers.sh
  e2e/scripts/shannon_preliminary_services_test.sh
  e2e/service_test.go
  gateway/request.go
Labels: testing

#305 [Tooling] Increasing the load on PATH performance
  e2e/config/.grove.archival.e2e_load_test.config.yaml
  e2e/config/.grove.e2e_load_test.config.yaml
  e2e/config/e2e_load_test.config.tmpl.yaml
  e2e/config/services_shannon.yaml
  e2e/config_test.go
Labels: testing, tooling

#273 [Logging] Use probabilistic debug info logging for rare events
  go.mod
  go.sum
  metrics/protocol/protocol.go
  metrics/protocol/shannon/metrics.go
  metrics/qos/evm/metrics.go
  metrics/qos/solana/metrics.go
  observation/qos/evm_interpreter.go
  observation/qos/solana_interpreter.go
  protocol/shannon/observation.go
  protocol/shannon/protocol.go
  qos/http.go
Labels: tooling

#309 Minor error improvements in logging
  cmd/data.go
  cmd/main.go
  cmd/morse.go
  cmd/shannon.go
  e2e/docker_test.go
  e2e/service_evm_test.go
  e2e/service_solana_test.go
  protocol/morse/context.go
  protocol/morse/errors.go
  protocol/shannon/protocol.go
  qos/cometbft/observe.go
  qos/cometbft/store.go
  qos/evm/endpoint_selection.go
  qos/evm/endpoint_store.go
  qos/evm/service_state.go
  qos/jsonrpc/params.go
  qos/solana/observe.go
Labels: documentation

#311 [Testing] Logging improvements, better archival checks, and improved load test scripts
  config/service_qos_config.go
  e2e/config/services_shannon.yaml
  e2e/config_test.go
  e2e/main_test.go
  e2e/service_evm_test.go
  e2e/service_solana_test.go
  e2e/vegeta_test.go
  gateway/request_context.go
  protocol/shannon/context.go
  protocol/shannon/endpoint.go
  qos/cometbft/state.go
  qos/cometbft/store.go
  qos/evm/endpoint.go
  qos/evm/endpoint_selection.go
  qos/evm/request_validator.go
  qos/evm/service_state.go
  qos/evm/state_archival.go
  qos/solana/endpoint.go
  qos/solana/request_validator.go
  qos/solana/response_getepochinfo.go
  qos/solana/response_gethealth.go
  qos/solana/state.go
  qos/solana/store.go
  websockets/bridge.go
  websockets/connection.go
Labels: testing

#315 build multiarch quickly
  .github/workflows/main-build.yml
  .serena/project.yml
  Dockerfile.release
  makefiles/release.mk
Labels: infra

#316 [SERVICE] Revised service IDs for onchain cleanup
  api/path_openapi.yaml
  config/service_qos_config.go
  docusaurus/docs/learn/qos/1_supported_services.md
  e2e/config/.grove.archival.e2e_load_test.config.yaml
  e2e/config/.grove.e2e_load_test.config.yaml
  e2e/config/services.schema.yaml
  e2e/config/services_shannon.yaml
  e2e/scripts/shannon_preliminary_services_test.sh
  makefiles/test.mk
  qos/evm/state_archival.go
Labels: enhancement, code health, e2e

#318 feat: add Prometheus metric to expose PATH version information
  .gitignore
  .serena/memories/code_style_conventions.md
  .serena/memories/metrics_patterns.md
  .serena/memories/project_overview.md
  .serena/memories/suggested_commands.md
  .serena/memories/task_completion_checklist.md
  cmd/main.go
  metrics/gateway.go
Labels: infra

#321 [QoS][EVM] Fix: QoS handles malformed endpoint responses for all requests
  e2e/config_test.go
  local/kind-config.yaml
  observation/qos/evm.pb.go
  proto/path/qos/evm.proto
  qos/evm/endpoint.go
  qos/evm/endpoint_selection.go
  qos/evm/endpoint_store.go
  qos/evm/response.go
  qos/evm/response_generic.go
  qos/evm/service_state.go
  qos/solana/response_generic.go
Labels: enhancement, qos, evm

#319 [QoS] Fix & improve perceived block number updates and validation
  qos/evm/check_blocknumber.go
  qos/evm/endpoint_selection.go
  qos/evm/service_state.go
Labels: qos
